repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, numpy]
        args: [--config-file=pyproject.toml]

  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: uv run pytest --no-header -q
        language: system
        pass_filenames: false
        always_run: true
